-- generated by tools/make_assets.py, do not edit
return {
 _about = "Frames are numbered left-to-right, top-to-bottom. origin = the pixel that sits on the ground / entity position. Render at 240x160 and only ever scale by whole numbers.",
 screen = {240, 160},
 tile = 16,
 palette = "palette/gusen-master.gpl",
 assets = {
  overworld = {
   file = "tiles/overworld.png",
   size = {256, 112},
   frame = {16, 16},
   frames = 112,
   animations = {
    water = {
     frames = {38, 54, 70},
     ms = 250,
     note = "every water tile animates: add 16*k to the index"
    },
    flowers = {
     frames = {5, 6},
     ms = 500
    },
    tallgrass = {
     frames = {7, 8},
     ms = 500
    }
   },
   note = "Autotile order per row: nw n ne inner-nw inner-ne / w c e inner-sw inner-se / sw s se c2 c3",
   tiles = {
    grass_a = 0,
    grass_b = 1,
    grass_c = 2,
    grass_redflowers = 3,
    grass_yellowflowers = 4,
    flowers_sway_0 = 5,
    flowers_sway_1 = 6,
    tallgrass_0 = 7,
    tallgrass_1 = 8,
    tallgrass_cut = 9,
    bush = 10,
    bush_cut = 11,
    rock_small = 12,
    rock_big = 13,
    path_nw = 16,
    path_n = 17,
    path_ne = 18,
    path_inw = 19,
    path_ine = 20,
    path_w = 21,
    path_c = 22,
    path_e = 23,
    path_isw = 24,
    path_ise = 25,
    path_sw = 26,
    path_s = 27,
    path_se = 28,
    path_c2 = 29,
    path_c3 = 30,
    water0_nw = 32,
    water0_n = 33,
    water0_ne = 34,
    water0_inw = 35,
    water0_ine = 36,
    water0_w = 37,
    water0_c = 38,
    water0_e = 39,
    water0_isw = 40,
    water0_ise = 41,
    water0_sw = 42,
    water0_s = 43,
    water0_se = 44,
    water0_c2 = 45,
    water0_c3 = 46,
    water1_nw = 48,
    water1_n = 49,
    water1_ne = 50,
    water1_inw = 51,
    water1_ine = 52,
    water1_w = 53,
    water1_c = 54,
    water1_e = 55,
    water1_isw = 56,
    water1_ise = 57,
    water1_sw = 58,
    water1_s = 59,
    water1_se = 60,
    water1_c2 = 61,
    water1_c3 = 62,
    water2_nw = 64,
    water2_n = 65,
    water2_ne = 66,
    water2_inw = 67,
    water2_ine = 68,
    water2_w = 69,
    water2_c = 70,
    water2_e = 71,
    water2_isw = 72,
    water2_ise = 73,
    water2_sw = 74,
    water2_s = 75,
    water2_se = 76,
    water2_c2 = 77,
    water2_c3 = 78,
    cliff_top_l = 80,
    cliff_top_m1 = 81,
    cliff_top_m2 = 82,
    cliff_top_r = 83,
    cliff_mid_l = 84,
    cliff_mid_m1 = 85,
    cliff_mid_m2 = 86,
    cliff_mid_r = 87,
    cliff_base_l = 88,
    cliff_base_m1 = 89,
    cliff_base_m2 = 90,
    cliff_base_r = 91,
    plateau_nw = 92,
    plateau_n = 93,
    plateau_ne = 94,
    plateau_w = 95,
    plateau_e = 96,
    sign = 97,
    chest_closed = 98,
    chest_open = 99,
    pot = 100,
    fence = 101,
    fence_post = 102,
    stump = 103
   }
  },
  tree = {
   file = "tiles/tree.png",
   size = {32, 40},
   origin = {16, 38}
  },
  cave_mouth = {
   file = "tiles/cave_mouth.png",
   size = {32, 32},
   note = "replaces 2x2 cliff tiles (top+mid rows)"
  },
  gusen_player = {
   file = "sprites/gusen_player.png",
   size = {48, 60},
   frame = {12, 15},
   frames = 16,
   origin = {6, 14},
   animations = {
    idle_down = {
     frames = {0},
     ms = 400
    },
    walk_down = {
     frames = {1, 0, 2, 0},
     ms = 120
    },
    attack_down = {
     frames = {3},
     ms = 200
    },
    idle_up = {
     frames = {4},
     ms = 400
    },
    walk_up = {
     frames = {5, 4, 6, 4},
     ms = 120
    },
    attack_up = {
     frames = {7},
     ms = 200
    },
    idle_left = {
     frames = {8},
     ms = 400
    },
    walk_left = {
     frames = {9, 8, 10, 8},
     ms = 120
    },
    attack_left = {
     frames = {11},
     ms = 200
    },
    idle_right = {
     frames = {12},
     ms = 400
    },
    walk_right = {
     frames = {13, 12, 14, 12},
     ms = 120
    },
    attack_right = {
     frames = {15},
     ms = 200
    }
   }
  },
  gusen_shadow = {
   file = "sprites/gusen_shadow.png",
   size = {36, 60},
   frame = {12, 15},
   frames = 12,
   origin = {6, 14},
   animations = {
    walk_down = {
     frames = {0, 1},
     ms = 180
    },
    attack_down = {
     frames = {2},
     ms = 250
    },
    walk_up = {
     frames = {3, 4},
     ms = 180
    },
    attack_up = {
     frames = {5},
     ms = 250
    },
    walk_left = {
     frames = {6, 7},
     ms = 180
    },
    attack_left = {
     frames = {8},
     ms = 250
    },
    walk_right = {
     frames = {9, 10},
     ms = 180
    },
    attack_right = {
     frames = {11},
     ms = 250
    }
   }
  },
  gusen_bat = {
   file = "sprites/gusen_bat.png",
   size = {48, 16},
   frame = {16, 16},
   frames = 3,
   origin = {8, 15},
   animations = {
    fly = {
     frames = {0, 1, 2, 1},
     ms = 90
    }
   }
  },
  gusen_boss = {
   file = "sprites/gusen_boss.png",
   size = {96, 32},
   frame = {32, 32},
   frames = 3,
   origin = {16, 31},
   animations = {
    idle = {
     frames = {0, 1},
     ms = 350
    },
    telegraph = {
     frames = {2},
     ms = 600
    }
   }
  },
  gusen_npcs = {
   file = "sprites/gusen_npcs.png",
   size = {48, 120},
   frame = {12, 15},
   frames = 32,
   origin = {6, 14},
   animations = {
    npc1_down = {
     frames = {0},
     ms = 0
    },
    npc1_up = {
     frames = {1},
     ms = 0
    },
    npc1_left = {
     frames = {2},
     ms = 0
    },
    npc1_right = {
     frames = {3},
     ms = 0
    },
    npc2_down = {
     frames = {4},
     ms = 0
    },
    npc2_up = {
     frames = {5},
     ms = 0
    },
    npc2_left = {
     frames = {6},
     ms = 0
    },
    npc2_right = {
     frames = {7},
     ms = 0
    },
    dinggusen_down = {
     frames = {8},
     ms = 0
    },
    dinggusen_up = {
     frames = {9},
     ms = 0
    },
    dinggusen_left = {
     frames = {10},
     ms = 0
    },
    dinggusen_right = {
     frames = {11},
     ms = 0
    },
    gressgusen_down = {
     frames = {12},
     ms = 0
    },
    gressgusen_up = {
     frames = {13},
     ms = 0
    },
    gressgusen_left = {
     frames = {14},
     ms = 0
    },
    gressgusen_right = {
     frames = {15},
     ms = 0
    },
    lanternegusen_down = {
     frames = {16},
     ms = 0
    },
    lanternegusen_up = {
     frames = {17},
     ms = 0
    },
    lanternegusen_left = {
     frames = {18},
     ms = 0
    },
    lanternegusen_right = {
     frames = {19},
     ms = 0
    },
    lunagusen_down = {
     frames = {20},
     ms = 0
    },
    lunagusen_up = {
     frames = {21},
     ms = 0
    },
    lunagusen_left = {
     frames = {22},
     ms = 0
    },
    lunagusen_right = {
     frames = {23},
     ms = 0
    },
    wirelessgusen_down = {
     frames = {24},
     ms = 0
    },
    wirelessgusen_up = {
     frames = {25},
     ms = 0
    },
    wirelessgusen_left = {
     frames = {26},
     ms = 0
    },
    wirelessgusen_right = {
     frames = {27},
     ms = 0
    },
    sprite_down = {
     frames = {28},
     ms = 0
    },
    sprite_up = {
     frames = {29},
     ms = 0
    },
    sprite_left = {
     frames = {30},
     ms = 0
    },
    sprite_right = {
     frames = {31},
     ms = 0
    }
   },
   note = "rows: npc1, npc2, dinggusen, gressgusen, lanternegusen, lunagusen, wirelessgusen, sprite"
  },
  heart = {
   file = "items/heart.png",
   size = {24, 15},
   frame = {12, 15},
   frames = 2,
   origin = {6, 13},
   animations = {
    bob = {
     frames = {0, 1},
     ms = 300
    }
   }
  },
  key = {
   file = "items/key.png",
   size = {36, 15},
   frame = {12, 15},
   frames = 3,
   origin = {6, 13},
   animations = {
    shine = {
     frames = {0, 1, 2},
     ms = 200
    }
   }
  },
  shard = {
   file = "items/shard.png",
   size = {36, 15},
   frame = {12, 15},
   frames = 3,
   origin = {6, 13},
   animations = {
    shine = {
     frames = {0, 1, 2},
     ms = 200
    }
   }
  },
  spaghetti = {
   file = "items/spaghetti.png",
   size = {12, 15},
   frame = {12, 15},
   frames = 1,
   origin = {6, 13}
  },
  sword = {
   file = "fx/sword.png",
   size = {128, 16},
   frame = {16, 16},
   frames = 8,
   animations = {
    up_right = {
     frames = {0, 1},
     ms = 100
    },
    up_left = {
     frames = {2, 3},
     ms = 100
    },
    down_right = {
     frames = {4, 5},
     ms = 100
    },
    down_left = {
     frames = {6, 7},
     ms = 100
    }
   },
   note = "Glodende Sverd remapped to the master palette; flips only, never rotated"
  },
  slash = {
   file = "fx/slash.png",
   size = {72, 96},
   frame = {24, 24},
   frames = 12,
   origin = {12, 12},
   animations = {
    slash_down = {
     frames = {0, 1, 2},
     ms = 50
    },
    slash_up = {
     frames = {3, 4, 5},
     ms = 50
    },
    slash_left = {
     frames = {6, 7, 8},
     ms = 50
    },
    slash_right = {
     frames = {9, 10, 11},
     ms = 50
    }
   }
  },
  poof = {
   file = "fx/poof.png",
   size = {64, 16},
   frame = {16, 16},
   frames = 4,
   origin = {8, 8},
   animations = {
    poof = {
     frames = {0, 1, 2, 3},
     ms = 70
    }
   }
  },
  hit = {
   file = "fx/hit.png",
   size = {24, 12},
   frame = {12, 12},
   frames = 2,
   origin = {6, 6},
   animations = {
    hit = {
     frames = {0, 1},
     ms = 50
    }
   }
  },
  dust = {
   file = "fx/dust.png",
   size = {24, 8},
   frame = {8, 8},
   frames = 3,
   origin = {4, 6},
   animations = {
    puff = {
     frames = {0, 1, 2},
     ms = 80
    }
   }
  },
  leaves = {
   file = "fx/leaves.png",
   size = {48, 16},
   frame = {16, 16},
   frames = 3,
   origin = {8, 8},
   animations = {
    cut = {
     frames = {0, 1, 2},
     ms = 80
    }
   }
  },
  spores = {
   file = "fx/spores.png",
   size = {24, 8},
   frame = {8, 8},
   frames = 3,
   origin = {4, 4},
   animations = {
    drift = {
     frames = {0, 1, 2},
     ms = 150
    }
   }
  },
  shadow = {
   file = "fx/shadow.png",
   size = {10, 4},
   origin = {5, 2},
   note = "50% black, drawn under every actor (GBA alpha-blend layer)"
  },
  floor_planks = {
   file = "mega/floor_planks.png",
   size = {16, 16},
   note = "interior: house floor; tiles seamlessly. From Mega_Spritesheet.ase [128, 64, 144, 80]; 5 colours",
   category = "interior"
  },
  floor_planks_dark = {
   file = "mega/floor_planks_dark.png",
   size = {16, 16},
   note = "interior: cellar / Lanterne-Gusen's dark house. From Mega_Spritesheet.ase [128, 48, 144, 64]; 5 colours",
   category = "interior"
  },
  stool = {
   file = "mega/stool.png",
   size = {14, 11},
   note = "interior: seating around tables. From Mega_Spritesheet.ase [48, 92, 64, 112]; 3 colours",
   category = "interior"
  },
  chair = {
   file = "mega/chair.png",
   size = {14, 19},
   note = "interior: seating. From Mega_Spritesheet.ase [64, 90, 80, 112]; 5 colours",
   category = "interior"
  },
  armchair = {
   file = "mega/armchair.png",
   size = {15, 18},
   note = "interior: living corner (mirror in engine for the other side). From Mega_Spritesheet.ase [80, 90, 96, 112]; 5 colours",
   category = "interior"
  },
  sofa = {
   file = "mega/sofa.png",
   size = {46, 14},
   note = "interior: living corner. From Mega_Spritesheet.ase [128, 94, 176, 112]; 7 colours",
   category = "interior"
  },
  nightstand = {
   file = "mega/nightstand.png",
   size = {14, 30},
   note = "interior: against walls; can hide a key. From Mega_Spritesheet.ase [48, 112, 64, 144]; 6 colours",
   category = "interior"
  },
  dresser = {
   file = "mega/dresser.png",
   size = {30, 30},
   note = "interior: shop counter / bedroom. From Mega_Spritesheet.ase [80, 112, 112, 144]; 6 colours",
   category = "interior"
  },
  cabinet = {
   file = "mega/cabinet.png",
   size = {30, 30},
   note = "interior: shop counter / kitchen. From Mega_Spritesheet.ase [112, 112, 144, 144]; 6 colours",
   category = "interior"
  },
  bookshelf = {
   file = "mega/bookshelf.png",
   size = {30, 30},
   note = "interior: Luna-Gusen's house; readable books = hints. From Mega_Spritesheet.ase [144, 112, 176, 144]; 30 colours (over the GBA 15-colour limit: reduce in the palette pass)",
   category = "interior"
  },
  table_big = {
   file = "mega/table_big.png",
   size = {46, 46},
   note = "interior: restaurant's shared dining table, food on top. From Mega_Spritesheet.ase [0, 96, 48, 144]; 5 colours",
   category = "interior"
  },
  table_big_wood = {
   file = "mega/table_big_wood.png",
   size = {46, 46},
   note = "interior: kitchen worktable / village market stall top. From Mega_Spritesheet.ase [0, 144, 48, 192]; 5 colours",
   category = "interior"
  },
  table_pedestal = {
   file = "mega/table_pedestal.png",
   size = {31, 23},
   note = "interior: Luna-Gusen's house / castle. From Mega_Spritesheet.ase [96, 214, 129, 240]; 7 colours",
   category = "interior"
  },
  table_small = {
   file = "mega/table_small.png",
   size = {14, 14},
   note = "interior: small table. From Mega_Spritesheet.ase [48, 144, 64, 160]; 6 colours",
   category = "interior"
  },
  table_red = {
   file = "mega/table_red.png",
   size = {14, 14},
   note = "interior: Spaghetti-Gusen's restaurant. From Mega_Spritesheet.ase [48, 160, 64, 176]; 8 colours",
   category = "interior"
  },
  table_red2 = {
   file = "mega/table_red2.png",
   size = {14, 14},
   note = "interior: Spaghetti-Gusen's restaurant. From Mega_Spritesheet.ase [64, 160, 80, 176]; 8 colours",
   category = "interior"
  },
  table_green = {
   file = "mega/table_green.png",
   size = {14, 14},
   note = "interior: Spaghetti-Gusen's restaurant. From Mega_Spritesheet.ase [48, 176, 64, 192]; 8 colours",
   category = "interior"
  },
  table_square = {
   file = "mega/table_square.png",
   size = {14, 14},
   note = "interior: Spaghetti-Gusen's restaurant. From Mega_Spritesheet.ase [64, 176, 80, 192]; 8 colours",
   category = "interior"
  },
  side_table = {
   file = "mega/side_table.png",
   size = {12, 11},
   note = "interior: shop display / next to armchair. From Mega_Spritesheet.ase [80, 160, 96, 176]; 6 colours",
   category = "interior"
  },
  side_table2 = {
   file = "mega/side_table2.png",
   size = {12, 14},
   note = "interior: shop display. From Mega_Spritesheet.ase [80, 176, 96, 192]; 6 colours",
   category = "interior"
  },
  cobble = {
   file = "mega/cobble.png",
   size = {16, 16},
   note = "stone: 16x16 cobblestone tile (the texture repeats every 16px, so it tiles seamlessly): plazas, castle, cave floors. From Mega_Spritesheet.ase [81, 59, 97, 75]; 7 colours",
   category = "stone"
  },
  cobble_patch = {
   file = "mega/cobble_patch.png",
   size = {48, 32},
   note = "stone: soft-edged cobble patch to drop on grass (shrine clearings, ruins). From Mega_Spritesheet.ase [80, 48, 128, 80]; 7 colours",
   category = "stone"
  },
  stand_tall = {
   file = "mega/stand_tall.png",
   size = {12, 20},
   note = "interior: indoor candle stand, unlit. From Mega_Spritesheet.ase [96, 168, 112, 192]; 6 colours",
   category = "interior"
  },
  stand_candle = {
   file = "mega/stand_candle.png",
   size = {12, 30},
   note = "interior: indoor candle stand, lit = checkpoint. From Mega_Spritesheet.ase [112, 160, 128, 192]; 14 colours",
   category = "interior"
  },
  window_view = {
   file = "mega/window_view.png",
   size = {21, 19},
   note = "interior: back-wall window. From Mega_Spritesheet.ase [68, 260, 92, 283]; 11 colours",
   category = "interior"
  },
  door = {
   file = "mega/door.png",
   size = {16, 25},
   note = "house: house door (exterior and interior). From Mega_Spritesheet.ase [46, 260, 66, 289]; 11 colours",
   category = "house"
  },
  window_small = {
   file = "mega/window_small.png",
   size = {16, 16},
   note = "house: house exterior window. From Mega_Spritesheet.ase [144, 56, 160, 72]; 4 colours",
   category = "house"
  },
  rug = {
   file = "mega/rug.png",
   size = {48, 11},
   note = "interior: doormat / under tables. From Mega_Spritesheet.ase [46, 289, 98, 304]; 15 colours",
   category = "interior"
  },
  potted_plant = {
   file = "mega/potted_plant.png",
   size = {8, 20},
   note = "interior: decor. From Mega_Spritesheet.ase [144, 217, 156, 241]; 11 colours",
   category = "interior"
  },
  basket = {
   file = "mega/basket.png",
   size = {19, 28},
   note = "village: breakable container (like pots). From Mega_Spritesheet.ase [101, 272, 124, 304]; 5 colours",
   category = "village"
  },
  lantern = {
   file = "mega/lantern.png",
   size = {9, 10},
   note = "item: Lanterne-Gusen's lantern (key item; replaces the generated one). From Mega_Spritesheet.ase [129, 254, 142, 268]; 10 colours",
   category = "item"
  },
  wallet = {
   file = "mega/wallet.png",
   size = {10, 6},
   note = "item: wallet upgrade: carry more Penge. From Mega_Spritesheet.ase [129, 242, 143, 252]; 8 colours",
   category = "item"
  },
  cupcakes = {
   file = "mega/cupcakes.png",
   size = {10, 7},
   note = "food: shop: heals 1/2 heart. From Mega_Spritesheet.ase [97, 242, 111, 253]; 12 colours",
   category = "food"
  },
  salad = {
   file = "mega/salad.png",
   size = {21, 9},
   note = "food: shop: heals 1 heart. From Mega_Spritesheet.ase [100, 258, 128, 271]; 14 colours",
   category = "food"
  },
  roast = {
   file = "mega/roast.png",
   size = {13, 7},
   note = "food: shop: heals 2 hearts. From Mega_Spritesheet.ase [111, 242, 128, 253]; 6 colours",
   category = "food"
  },
  fruit_bowl = {
   file = "mega/fruit_bowl.png",
   size = {13, 10},
   note = "food: table decor / free snack. From Mega_Spritesheet.ase [128, 222, 145, 236]; 11 colours",
   category = "food"
  },
  pine = {
   file = "mega/pine.png",
   size = {16, 16},
   note = "forest: Skogen's tree; overlap in rows for dense forest walls. From Mega_Spritesheet.ase [0, 240, 16, 256]; 6 colours",
   category = "forest"
  },
  pine_trio = {
   file = "mega/pine_trio.png",
   size = {32, 24},
   note = "forest: ready-made cluster. From Mega_Spritesheet.ase [6, 262, 42, 290]; 6 colours",
   category = "forest"
  },
  log = {
   file = "mega/log.png",
   size = {16, 23},
   note = "forest: hollow log: something can hide inside. From Mega_Spritesheet.ase [270, 64, 290, 91]; 4 colours",
   category = "forest"
  },
  sunflower = {
   file = "mega/sunflower.png",
   size = {7, 14},
   note = "garden: Gress-Gusen's garden. From Mega_Spritesheet.ase [132, 32, 145, 48]; 6 colours",
   category = "garden"
  },
  white_flower = {
   file = "mega/white_flower.png",
   size = {8, 14},
   note = "garden: Gress-Gusen's garden. From Mega_Spritesheet.ase [180, 20, 191, 37]; 3 colours",
   category = "garden"
  },
  throne = {
   file = "mega/throne.png",
   size = {27, 33},
   note = "castle: Skyggekongen's throne. From Mega_Spritesheet.ase [145, 252, 176, 289]; 9 colours",
   category = "castle"
  },
  candle_dish = {
   file = "mega/candle_dish.png",
   size = {64, 16},
   frame = {16, 16},
   frames = 4,
   origin = {8, 15},
   animations = {
    lit = {
     frames = {0},
     ms = 0
    },
    blow_out = {
     frames = {0, 1, 2, 3},
     ms = 500
    },
    relight = {
     frames = {3, 2, 1, 0},
     ms = 150
    }
   },
   note = "indoor checkpoint candle (Mega sheet), same timing as Blåse ut lys"
  },
  interior = {
   file = "tiles/interior.png",
   size = {256, 32},
   frame = {16, 16},
   frames = 32,
   note = "side/front pieces are drawn on floor_planks; use art_tiles.interior_tiles() overlays for other floors",
   tiles = {
    floor_planks = 0,
    floor_planks_dark = 1,
    cobble = 2,
    wall_top_l = 3,
    wall_top = 4,
    wall_top_r = 5,
    wall_bottom_l = 6,
    wall_bottom = 7,
    wall_bottom_r = 8,
    side_l = 9,
    side_r = 10,
    front_l = 11,
    front = 12,
    front_r = 13,
    void = 14,
    cap_side_l = 16,
    cap_side_r = 17,
    cap_front = 18,
    cap_front_l = 19,
    cap_front_r = 20
   }
  },
  font = {
   file = "ui/font.png",
   size = {128, 70},
   frame = {8, 10},
   frames = 112
  },
  dialog_box = {
   file = "ui/dialog_box.png",
   size = {24, 24},
   note = "9-slice, 8px borders"
  },
  hearts = {
   file = "ui/hearts.png",
   size = {24, 8},
   frame = {8, 8},
   frames = 3,
   note = "full, half, empty"
  },
  icons = {
   file = "ui/icons.png",
   size = {24, 8},
   frame = {8, 8},
   frames = 3,
   note = "coin, key, shard"
  },
  cursor = {
   file = "ui/cursor.png",
   size = {7, 7}
  },
  more_arrow = {
   file = "ui/more_arrow.png",
   size = {14, 6},
   frame = {7, 6},
   frames = 2,
   animations = {
    bob = {
     frames = {0, 1},
     ms = 300
    }
   }
  },
  slot_a = {
   file = "ui/slot_a.png",
   size = {20, 20}
  },
  slot_b = {
   file = "ui/slot_b.png",
   size = {20, 20}
  },
  logo = {
   file = "ui/logo.png",
   size = {62, 20}
  },
  candle = {
   file = "legacy/candle.png",
   size = {48, 15},
   frame = {12, 15},
   frames = 4,
   origin = {6, 14},
   animations = {
    blow_out = {
     frames = {0, 1, 2, 3},
     ms = {500, 500, 500, 500},
     loop = false
    }
   },
   note = "exported from Blåse ut lys_12x15.ase"
  },
  frog = {
   file = "legacy/frog.png",
   size = {36, 15},
   frame = {12, 15},
   frames = 3,
   origin = {6, 14},
   animations = {
    bounce = {
     frames = {0, 1, 2},
     ms = {300, 150, 300},
     loop = true
    }
   },
   note = "exported from Bouncy Ball Frog_12x15.ase"
  },
  fluesopp = {
   file = "legacy/fluesopp.png",
   size = {24, 15},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    idle = {
     frames = {0, 1},
     ms = {500, 500},
     loop = true
    }
   },
   note = "exported from Fluesopp med sporer_12x15.ase"
  },
  coin = {
   file = "legacy/coin.png",
   size = {36, 15},
   frame = {12, 15},
   frames = 3,
   origin = {6, 14},
   animations = {
    spin = {
     frames = {0, 1, 2},
     ms = {200, 200, 200},
     loop = true
    }
   },
   note = "exported from Penge_12x15.ase"
  },
  microwave = {
   file = "legacy/microwave.png",
   size = {36, 15},
   frame = {12, 15},
   frames = 3,
   origin = {6, 14},
   animations = {
    explode = {
     frames = {0, 1, 2},
     ms = {500, 100, 300},
     loop = false
    }
   },
   note = "exported from Eksploderende Mikrobølgeovn_12x15.ase"
  },
  windgrass = {
   file = "legacy/windgrass.png",
   size = {24, 15},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    sway = {
     frames = {0, 1},
     ms = {500, 500},
     loop = true
    }
   },
   note = "exported from Vind i gress_12x15.ase"
  },
  flower_grow = {
   file = "legacy/flower_grow.png",
   size = {224, 32},
   frame = {32, 32},
   frames = 7,
   origin = {16, 31},
   animations = {
    grow = {
     frames = {0, 1, 2, 3, 4, 5, 6},
     ms = {1000, 1000, 1000, 1000, 1000, 1000, 1000},
     loop = false
    }
   },
   note = "exported from Voksende rød blomst_32x32.ase"
  },
  player = {
   file = "legacy/player.png",
   size = {12, 30},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    left = {
     frames = {0},
     ms = 0
    },
    right = {
     frames = {1},
     ms = 0
    }
   }
  },
  npc1 = {
   file = "legacy/npc1.png",
   size = {12, 30},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    left = {
     frames = {0},
     ms = 0
    },
    right = {
     frames = {1},
     ms = 0
    }
   }
  },
  npc2 = {
   file = "legacy/npc2.png",
   size = {12, 30},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    left = {
     frames = {0},
     ms = 0
    },
    right = {
     frames = {1},
     ms = 0
    }
   }
  },
  dinggusen = {
   file = "legacy/dinggusen.png",
   size = {12, 30},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    left = {
     frames = {0},
     ms = 0
    },
    right = {
     frames = {1},
     ms = 0
    }
   }
  },
  gressgusen = {
   file = "legacy/gressgusen.png",
   size = {12, 30},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    left = {
     frames = {0},
     ms = 0
    },
    right = {
     frames = {1},
     ms = 0
    }
   }
  },
  lanternegusen = {
   file = "legacy/lanternegusen.png",
   size = {12, 30},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    left = {
     frames = {0},
     ms = 0
    },
    right = {
     frames = {1},
     ms = 0
    }
   }
  },
  lunagusen = {
   file = "legacy/lunagusen.png",
   size = {12, 30},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    left = {
     frames = {0},
     ms = 0
    },
    right = {
     frames = {1},
     ms = 0
    }
   }
  },
  spaghettigusen = {
   file = "legacy/spaghettigusen.png",
   size = {12, 30},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    left = {
     frames = {0},
     ms = 0
    },
    right = {
     frames = {1},
     ms = 0
    }
   }
  },
  wirelessgusen = {
   file = "legacy/wirelessgusen.png",
   size = {12, 30},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    left = {
     frames = {0},
     ms = 0
    },
    right = {
     frames = {1},
     ms = 0
    }
   }
  },
  generatorgusen = {
   file = "legacy/generatorgusen.png",
   size = {12, 30},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    left = {
     frames = {0},
     ms = 0
    },
    right = {
     frames = {1},
     ms = 0
    }
   }
  },
  sprite = {
   file = "legacy/sprite.png",
   size = {12, 30},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    left = {
     frames = {0},
     ms = 0
    },
    right = {
     frames = {1},
     ms = 0
    }
   }
  },
  sprite2 = {
   file = "legacy/sprite2.png",
   size = {12, 30},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    left = {
     frames = {0},
     ms = 0
    },
    right = {
     frames = {1},
     ms = 0
    }
   }
  },
  sprite3 = {
   file = "legacy/sprite3.png",
   size = {12, 30},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    left = {
     frames = {0},
     ms = 0
    },
    right = {
     frames = {1},
     ms = 0
    }
   }
  },
  sprite4 = {
   file = "legacy/sprite4.png",
   size = {12, 30},
   frame = {12, 15},
   frames = 2,
   origin = {6, 14},
   animations = {
    left = {
     frames = {0},
     ms = 0
    },
    right = {
     frames = {1},
     ms = 0
    }
   }
  }
 }
}
