-- Gusenby: the village. A scrolling area (2x2 screens).
return {
    kind = "area",
    theme = "overworld",
    rows = {
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "HHHHHHHHHHHHHHHHHHHHHHHHHHHHHH",
        "CCCCCCKKCCCCCCCCCCCCCCCCCCCCCC",
        "CCCCCCkkCCCCCCCCCCCCCDDCCCCCCC",
        "......PP.............PP.......",
        "..,...PP.............PP...;...",
        "......PPPPPPPPPPPPPPPPP.......",
        "......PPPPPPPPPPPPPPPPP.......",
        "..............PP..............",
        "..WWWW........PP.........,....",
        "..WWWW........PP..............",
        "..WWWW........PP..............",
        "..WWWW........PPPPPPPPPPPPPPPP",
        "..............PPPPPPPPPPPPPPPP",
        "....;.........................",
        "..............................",
        "..................,...........",
        "TT...........TT...........TTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    },
    spawns = {
        start = { 15, 9, dir = "down" },
        from_kro = { 21, 5, dx = 8, dir = "down" },
        from_cave = { 6, 5, dx = 8, dir = "down" },
        east_gate = { 28, 13, dy = 8, dir = "left" },
    },
    exits = {
        east = { to = "skogen", spawn = "west", span = { 13, 14 } },
    },
    objects = {
        { "cave", 6, 3 },
        { "door", 6, 4, w = 2, to = "hule1", spawn = "south" },
        { "candle", 5, 5, talk = "candle_lit" },
        { "candle", 8, 5, talk = "candle_lit" },
        { "mega", 21, 4, name = "door", dx = 8 },
        { "door", 21, 4, w = 2, to = "kro", spawn = "door" },
        { "mega", 19, 4, name = "window_small", dy = -6 },
        { "mega", 24, 4, name = "window_small", dy = -6 },
        { "sign", 9, 5, talk = "sign_gusenby" },
        { "sign", 20, 5, talk = "sign_kro" },
        { "tree", 1, 2 }, { "tree", 12, 2, dx = 4 }, { "tree", 17, 1 }, { "tree", 27, 2 },
        { "tree", 24, 10 }, { "tree", 9, 16 }, { "tree", 22, 17 },
        { "tallgrass_0", 18, 10 }, { "tallgrass_0", 19, 10 }, { "tallgrass_0", 20, 10 },
        { "tallgrass_0", 18, 11 }, { "tallgrass_0", 19, 11 },
        { "bush", 26, 8 }, { "bush", 27, 8 },
        { "rock_big", 11, 11 }, { "rock_small", 12, 12 }, { "rock_small", 7, 15 },
        { "flowers_sway_0", 3, 7 }, { "flowers_sway_0", 17, 16 },
        { "mega", 8, 10, name = "sunflower" }, { "mega", 9, 10, name = "sunflower", dx = -5 },
        { "mega", 8, 11, name = "white_flower", dx = 4 },
        { "stump", 27, 15 },
        { "chest_closed", 25, 16, talk = "chest_locked" },
        { "legacy", 3, 14, name = "frog" },
        { "npc", 11, 9, who = "lanternegusen", dir = "down", talk = "talk_lanterne", name = "name_lanterne" },
        { "npc", 7, 11, who = "gressgusen", dir = "left", talk = "talk_gress", name = "name_gress" },
    },
}
