-- Skogen: the forest east of Gusenby. A scrolling area; T = pine forest.
return {
    kind = "area",
    theme = "overworld",
    rows = {
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTT..........TTTTT.......TTTT",
        "TTT............TTT.....PP..TTT",
        "TT.....................PP...TT",
        "TT.....................PP...TT",
        "TT.....PPPPPPPPPPPPPPPPPP...TT",
        "TT.....PPPPPPPPPPPPPPPPPP...TT",
        "TT.....PP...................TT",
        "TTT....PP...................TT",
        "TTT....PP..................TTT",
        "TT.....PP...................TT",
        "TT.....PP...................TT",
        "PPPPPPPPP...................TT",
        "PPPPPPPPP.......,...........TT",
        "TT..........................TT",
        "TTT.............;..........TTT",
        "TTTT...........TT.........TTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
        "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT",
    },
    spawns = {
        start = { 1, 13, dy = 8, dir = "right" },
        west = { 1, 13, dy = 8, dir = "right" },
    },
    exits = {
        west = { to = "gusenby", spawn = "east_gate", span = { 13, 14 } },
    },
    objects = {
        -- the shrine: a cobblestone clearing and a candle someone blew out
        { "at", 21 * 16, 2 * 16, name = "cobble_patch" },
        { "candle", 22, 2, dx = 8, dy = 4, lit = false, talk = "candle_out" },
        { "sheet", 20, 3, sheet = "gusen_shadow", anim = "walk_right", talk = "shadow_hiss" },
        { "sheet", 16, 4, sheet = "gusen_bat", anim = "fly", solid = false },
        { "sign", 9, 12, talk = "sign_skogen" },
        { "mega", 12, 10, name = "log" },
        { "mega", 18, 13, name = "pine_trio" },
        { "legacy", 14, 12, name = "fluesopp" },
        { "legacy", 20, 15, name = "fluesopp" },
        { "legacy", 10, 15, name = "frog" },
        { "tallgrass_0", 3, 9 }, { "tallgrass_0", 4, 9 }, { "tallgrass_0", 3, 10 },
        { "tallgrass_0", 4, 10 }, { "tallgrass_0", 5, 10 },
        { "mega", 5, 4, name = "white_flower" }, { "mega", 17, 9, name = "white_flower" },
        { "mega", 26, 11, name = "white_flower" },
        { "rock_big", 25, 14 }, { "bush", 13, 4 }, { "bush", 3, 15 },
    },
}
