-- generated by tools/make_assets.py, do not edit
return {
 cell = {8, 10},
 columns = 16,
 baseline = 7,
 line_height = 11,
 letter_spacing = 1,
 glyphs = {
  [" "] = {
   index = 0,
   width = 3
  },
  ["!"] = {
   index = 1,
   width = 1
  },
  ["\""] = {
   index = 2,
   width = 3
  },
  ["#"] = {
   index = 3,
   width = 5
  },
  ["$"] = {
   index = 4,
   width = 5
  },
  ["%"] = {
   index = 5,
   width = 5
  },
  ["&"] = {
   index = 6,
   width = 5
  },
  ["'"] = {
   index = 7,
   width = 1
  },
  ["("] = {
   index = 8,
   width = 2
  },
  [")"] = {
   index = 9,
   width = 2
  },
  ["*"] = {
   index = 10,
   width = 5
  },
  ["+"] = {
   index = 11,
   width = 5
  },
  [","] = {
   index = 12,
   width = 2
  },
  ["-"] = {
   index = 13,
   width = 3
  },
  ["."] = {
   index = 14,
   width = 1
  },
  ["/"] = {
   index = 15,
   width = 5
  },
  ["0"] = {
   index = 16,
   width = 5
  },
  ["1"] = {
   index = 17,
   width = 3
  },
  ["2"] = {
   index = 18,
   width = 5
  },
  ["3"] = {
   index = 19,
   width = 5
  },
  ["4"] = {
   index = 20,
   width = 5
  },
  ["5"] = {
   index = 21,
   width = 5
  },
  ["6"] = {
   index = 22,
   width = 5
  },
  ["7"] = {
   index = 23,
   width = 5
  },
  ["8"] = {
   index = 24,
   width = 5
  },
  ["9"] = {
   index = 25,
   width = 5
  },
  [":"] = {
   index = 26,
   width = 1
  },
  [";"] = {
   index = 27,
   width = 2
  },
  ["<"] = {
   index = 28,
   width = 4
  },
  ["="] = {
   index = 29,
   width = 4
  },
  [">"] = {
   index = 30,
   width = 4
  },
  ["?"] = {
   index = 31,
   width = 5
  },
  ["@"] = {
   index = 32,
   width = 5
  },
  A = {
   index = 33,
   width = 5
  },
  B = {
   index = 34,
   width = 5
  },
  C = {
   index = 35,
   width = 5
  },
  D = {
   index = 36,
   width = 5
  },
  E = {
   index = 37,
   width = 5
  },
  F = {
   index = 38,
   width = 5
  },
  G = {
   index = 39,
   width = 5
  },
  H = {
   index = 40,
   width = 5
  },
  I = {
   index = 41,
   width = 3
  },
  J = {
   index = 42,
   width = 5
  },
  K = {
   index = 43,
   width = 5
  },
  L = {
   index = 44,
   width = 5
  },
  M = {
   index = 45,
   width = 5
  },
  N = {
   index = 46,
   width = 5
  },
  O = {
   index = 47,
   width = 5
  },
  P = {
   index = 48,
   width = 5
  },
  Q = {
   index = 49,
   width = 5
  },
  R = {
   index = 50,
   width = 5
  },
  S = {
   index = 51,
   width = 5
  },
  T = {
   index = 52,
   width = 5
  },
  U = {
   index = 53,
   width = 5
  },
  V = {
   index = 54,
   width = 5
  },
  W = {
   index = 55,
   width = 5
  },
  X = {
   index = 56,
   width = 5
  },
  Y = {
   index = 57,
   width = 5
  },
  Z = {
   index = 58,
   width = 5
  },
  ["["] = {
   index = 59,
   width = 2
  },
  ["\\"] = {
   index = 60,
   width = 5
  },
  ["]"] = {
   index = 61,
   width = 2
  },
  ["^"] = {
   index = 62,
   width = 5
  },
  _ = {
   index = 63,
   width = 5
  },
  ["`"] = {
   index = 64,
   width = 2
  },
  a = {
   index = 65,
   width = 5
  },
  b = {
   index = 66,
   width = 5
  },
  c = {
   index = 67,
   width = 5
  },
  d = {
   index = 68,
   width = 5
  },
  e = {
   index = 69,
   width = 5
  },
  f = {
   index = 70,
   width = 4
  },
  g = {
   index = 71,
   width = 5
  },
  h = {
   index = 72,
   width = 5
  },
  i = {
   index = 73,
   width = 1
  },
  j = {
   index = 74,
   width = 3
  },
  k = {
   index = 75,
   width = 4
  },
  l = {
   index = 76,
   width = 2
  },
  m = {
   index = 77,
   width = 5
  },
  n = {
   index = 78,
   width = 5
  },
  o = {
   index = 79,
   width = 5
  },
  p = {
   index = 80,
   width = 5
  },
  q = {
   index = 81,
   width = 5
  },
  r = {
   index = 82,
   width = 4
  },
  s = {
   index = 83,
   width = 5
  },
  t = {
   index = 84,
   width = 4
  },
  u = {
   index = 85,
   width = 5
  },
  v = {
   index = 86,
   width = 5
  },
  w = {
   index = 87,
   width = 5
  },
  x = {
   index = 88,
   width = 5
  },
  y = {
   index = 89,
   width = 5
  },
  z = {
   index = 90,
   width = 5
  },
  ["{"] = {
   index = 91,
   width = 3
  },
  ["|"] = {
   index = 92,
   width = 1
  },
  ["}"] = {
   index = 93,
   width = 3
  },
  ["~"] = {
   index = 94,
   width = 5
  },
  ["Æ"] = {
   index = 95,
   width = 6
  },
  ["Ø"] = {
   index = 96,
   width = 5
  },
  ["Å"] = {
   index = 97,
   width = 5
  },
  ["æ"] = {
   index = 98,
   width = 7
  },
  ["ø"] = {
   index = 99,
   width = 5
  },
  ["å"] = {
   index = 100,
   width = 5
  },
  ["♥"] = {
   index = 101,
   width = 5
  }
 }
}
