"""Pickups (12x15 cells like Penge_12x15), weapon, effects and HUD icons."""
import math
from pixel import *

INK = {"#": "000000", "e": "170000", "d": "2b0000", "n": "460000",
       "r": "c50000", "R": "ff0000", "p": "ffe3e3", "o": "ffffff"}
GOLD = {"j": "f9a31b", "J": "ffd541", "Z": "fffc40", "O": "fa6a0a"}


# --- pickups, 12x15 -------------------------------------------------------
def heart_pickup():
    return frames('''
        ............ ............
        ............ ............
        ............ ............
        ............ ............
        ..##...##... ............
        .#RR#.#RR#.. ..##...##...
        #RpRR#RRRr#. .#RR#.#RR#..
        #RRRRRRRRr#. #RppR#RRRr#.
        #RRRRRRRRr#. #RpRRRRRRr#.
        .#RRRRRRr#.. #RRRRRRRRr#.
        ..#RRRRr#... .#RRRRRRr#..
        ...#RRr#.... ..#RRRRr#...
        ....#r#..... ...#RRr#....
        .....#...... ....#r#.....
        ............ .....#......
    ''', INK, 12, 15)


def key_pickup():
    """Gold key in the Penge palette: light top-left edge, dark right edge, no outline."""
    return frames('''
        ............ ............ ............
        ....ZZZ..... ....ZZZ..... ....ZZZ.....
        ...ZJJJj.... ...ZJZJj.... ...ZJJJj....
        ...ZJ.Jj.... ...ZJ.Jj.... ...ZJ.Jj....
        ...ZJJJj.... ...ZJJJj.... ...ZJJJj....
        ....ZJj..... ....ZJj..... ....ZZj.....
        ....ZJj..... ....ZJj..... ....ZZj.....
        ....ZJjj.... ....ZJjj.... ....ZJjj....
        ....ZJJOj... ....ZJJOj... ....ZJJOj...
        ....ZJj..... ....ZJj..... ....ZJj.....
        ....ZJJj.... ....ZJJj.... ....ZJJj....
        ....ZJOOj... ....ZJOOj... ....ZJOOj...
        .....jj..... .....jj..... .....jj.....
        ............ ............ ............
        ............ ............ ............
    ''', GOLD, 12, 15)


def shard_pickup():
    """Glodende skar: a shard of the sword's red glow. 3-frame glint like Penge."""
    return frames('''
        ............ ............ ............
        ............ ............ ............
        .....#...... .....#...... .....#......
        ....#p#..... ....#R#..... ....#R#.....
        ....#pR#.... ...#RpR#.... ...#RRp#....
        ...#pRRr#... ...#RpRr#... ...#RRpr#...
        ...#pRRr#... ...#RRpr#... ...#RRRp#...
        ..#pRRRrn#.. ..#RRRprn#.. ..#RRRRpn#..
        ..#RRRRrn#.. ..#RRRRpn#.. ..#RRRRrp#..
        ...#RRrn#... ...#RRrn#... ...#RRrn#...
        ...#Rrrn#... ...#Rrrn#... ...#Rrrn#...
        ....#rn#.... ....#rn#.... ....#rn#....
        .....##..... .....##..... .....##.....
        ............ ............ ............
        ............ ............ ............
    ''', INK, 12, 15)


def spaghetti_pickup():
    """Spaghetti-Gusen's cooking: heals 2 hearts."""
    k = {"#": "000000", "X": "dae0ea", "V": "b3b9d1", "v": "8b93af",
         "Y": "f4d29c", "U": "dba463", "I": "df3e23", "i": "b4202a", "g": "14a02e"}
    return art(parse_block('''
        ............
        ............
        ............
        ............
        ....#.#.....
        ...#Y#Y#....
        ..#YUYYIi#..
        .#YIiYUYIi#.
        #XXXXXXXXXV#
        #VXXXXXXXVv#
        .#VVXXXXVv#.
        ..#vVVVVv#..
        ...######...
        ............
        ............
    '''), k)


# --- weapon: Glodende Sverd remapped to the master palette -----------------
SWORD_REMAP = {"4f4f4f": "4a5462", "7f7f7f": "6d758d", "212121": "141013", "363636": "333941",
               "2b0507": "2b0000", "460000": "460000", "ed1c24": "c50000", "ff0000": "ff0000"}


def sword_orientations(sword_frames):
    """8 frames: [up-right, up-left, down-right, down-left] x [glow off, glow on]."""
    out = []
    for f in sword_frames:
        f = recolor(f, SWORD_REMAP)
        out.append([f, flip_h(f), flip_v(f), flip_h(flip_v(f))])
    return [o for pair in zip(*out) for o in pair]


def slash_arcs():
    """24x24 crescent smears, rows = down, up, left, right; 3 frames each."""
    size, c = 24, 11.5
    spans = [(-100, -30), (-100, 70), (0, 90)]  # degrees, 0 = facing direction, + = clockwise

    def frame(i):
        a0, a1 = spans[i]
        im = blank(size, size)
        px = im.load()
        for y in range(size):
            for x in range(size):
                dx, dy = x + 0.5 - c, y + 0.5 - c
                r = math.hypot(dx, dy)
                ang = math.degrees(math.atan2(dy, dx))
                if not (a0 <= ang <= a1) or not (5.5 <= r <= 11.5):
                    continue
                t = (ang - a0) / (a1 - a0)  # 0 = trailing end, 1 = leading edge
                if i == 2:
                    t *= 0.6
                if r > 10.5:
                    col = "ffe3e3" if t > 0.55 else ("ff0000" if t > 0.25 else "460000")
                elif r > 8.5:
                    col = "ff0000" if t > 0.35 else ("c50000" if t > 0.15 else "2b0000")
                elif r > 7:
                    col = "c50000" if t > 0.3 else "460000"
                else:
                    if t < 0.5:
                        continue
                    col = "460000"
                px[x, y] = rgba(col)
        return im

    right = [frame(i) for i in range(3)]
    left = [flip_h(f) for f in right]
    up = [rot90(f, 1) for f in right]
    down = [rot90(f, 3) for f in right]
    return down + up + left + right


# --- effects -------------------------------------------------------------
def poof():
    """Enemy death: black smoke + red embers, 16x16 x 4."""
    out = []
    specs = [
        (2.0, 3.2, "000000", "ff0000", 5.5),
        (4.0, 2.6, "000000", "ff0000", 7.0),
        (5.5, 2.0, "333941", "c50000", 7.5),
        (6.5, 1.2, "4a5462", "460000", 7.9),
    ]
    for i, (ring, pr, col, ember, er) in enumerate(specs):
        im = blank(16, 16)
        px = im.load()
        centers = [(7.5, 7.5)] if i == 0 else [
            (7.5 + ring * math.cos(math.radians(a)), 7.5 + ring * math.sin(math.radians(a)))
            for a in range(-90, 270, 72)]
        for y in range(16):
            for x in range(16):
                for (cx, cy) in centers:
                    if (x + 0.5 - cx) ** 2 + (y + 0.5 - cy) ** 2 <= pr * pr:
                        px[x, y] = rgba(col)
        for a in range(-54, 306, 72):
            ex = int(7.5 + er * math.cos(math.radians(a)))
            ey = int(7.5 + er * math.sin(math.radians(a)))
            if 0 <= ex < 16 and 0 <= ey < 16:
                px[ex, ey] = rgba(ember)
        if i == 0:
            px[7, 7] = rgba("ff0000")
            px[8, 7] = rgba("ffe3e3")
        out.append(im)
    return out


def hit_spark():
    return frames('''
        ....p....... ............
        ....p....... ............
        ....R....... .....R......
        p..RpR..p... ...R...R....
        .RRpppRR.... ....R.R.....
        ...RpR...... .R..p..R....
        ....R....... ....R.R.....
        ....p....... ...R...R....
        ....p....... .....R......
        ............ ............
        ............ ............
        ............ ............
    ''', INK, 12, 12)


def dust():
    k = {"X": "dae0ea", "V": "b3b9d1", "v": "8b93af"}
    return frames('''
        ........ ........ ........
        ........ ........ ........
        ........ ..XX.... .X...X..
        ...X.... .XXVX... ........
        ..XVV... .XVVVX.. ..V.....
        ...v.... ..VvV... .....v..
        ........ ........ ........
        ........ ........ ........
    ''', k, 8, 8)


def leaves():
    k = {"l": "59c135", "g": "14a02e", "d": "1a7a3e", "h": "9cdb43"}
    return frames('''
        ................ ................ ................
        ................ ................ .h............l.
        ................ ..h.......l..... ................
        .......l........ ................ ................
        .....h..g....... ................ ................
        ....ld.hd.l..... .l..........d.. ...........g....
        ......gl.d...... ................ ................
        .....d..lg...... ................ ................
        ................ ....g..h........ ................
        ................ ..........l..... ................
        ................ ................ ..d.............
        ................ ................ ...........d....
        ................ ................ ................
        ................ ........d....... ................
        ................ ................ .......l........
        ................ ................ ................
    ''', k, 16, 16)


def spores():
    """Spores for Fluesopp med sporer; pink mapped from DB32 d95763 -> AAP e86a73."""
    k = {"w": "ffffff", "V": "b3b9d1", "P": "e86a73"}
    return frames('''
        ........ ........ ........
        ........ ...w.... ..V.....
        ...w.... ..wPw... ........
        ..wPw... ...w.... .....V..
        ...w.... ........ ........
        ........ ......V. ...V....
        ........ ........ ........
        ........ ........ ........
    ''', k, 8, 8)


def shadow():
    """Drop shadow. The only sprite with partial alpha (GBA blend layer)."""
    im = blank(10, 4)
    px = im.load()
    for y in range(4):
        for x in range(10):
            if ((x + 0.5 - 5) / 5) ** 2 + ((y + 0.5 - 2) / 2) ** 2 <= 1:
                px[x, y] = (0, 0, 0, 96)
    return im


# --- HUD icons, 8x8 --------------------------------------------------------
def hud_hearts():
    k = dict(INK, S="333941", s="4a5462")
    return frames('''
        ........ ........ ........
        .##.##.. .##.##.. .##.##..
        #pR#RR#. #pR#ss#. #ss#ss#.
        #RRRRr#. #RRRSs#. #sSSSs#.
        .#RRr#.. .#RRS#.. .#sSS#..
        ..#r#... ..#rS... ..#S#...
        ...#.... ...#.... ...#....
        ........ ........ ........
    ''', k, 8, 8)


def hud_icons():
    k = dict(INK, **GOLD)
    return frames('''
        ..ZZZ... ..ZZZ... ...#....
        .ZJJJj.. .ZJ.Jj.. ..#p#...
        ZJJZJJj. .ZJJJj.. ..#pR#..
        ZJZJJJj. ..ZJj... .#pRr#..
        ZJJJZJj. ..ZJjj.. .#RRrn#.
        ZJJJJJj. ..ZJOj.. ..#Rrn#.
        .jJJJj.. ..ZJj... ...#n#..
        ..jjj... ...jj... ....#...
    ''', k, 8, 8)
